set(RETO_MATURITY "EP")
set(RETO_DESCRIPTION "")
set(RETO_GIT_ROOT_URL "https://gitlab-ci-token:28hjAC18fDaCya56Mow2@gitlab.vg-lab.es/nsviz/ReTo.git")
set(RETO_PACKAGE_URL "")
set(RETO_CI_URL "")
set(RETO_CI_PNG "")
set(RETO_ISSUES_URL "")
